### ISSUE TITLE
Any interest in libusb?

### ISSUE THREAD

**Issue by eduncan911** [GeertJohan/go.hid#9]
This is a fantastic Go library for HID devices!  Finally, after 6+ years of sitting on some unique USB HID devices, I saw this repo and sniffed out the commands for my device (though there are other types and models out there).

As I started to use go.hid, I quickly ran up against the limitations of the `hidapi` library!  In particular:

http://stackoverflow.com/questions/17706853/using-hidapi-how-can-you-query-the-raw-report-descriptor

```
HIDAPI does not provide functions for getting or parsing the report descriptor. Since HIDAPI is 
for talking to a custom devices, these devices will likely contain all or mostly vendor-defined 
report items anyway.
```

That's a bummer as I was attempting to query for and then enumerate over all report IDs and their descriptors as that's what my device uses.

So I am back to investigating into the `libusb` C++ cross-platform project.

https://github.com/libusb/libusb

**Comment by GeertJohan** [comment]
Hey @eduncan911, sorry for the very late reply. Did you make any progress in the meantime? Made a choice out of the two? I'm interested in seeing where you're going with this.

**Comment by eduncan911** [comment]
As life unfolds, many other projects came up.  :)  I didn't get to finish the prototyping code I was working on.

I started down the path of calling libusb from go.hid (option 1, but more device agnostic by just exposing the methods that wrap the underlying calls).  But my C++ skills is under-par and it was taking too long to make progress.

I do need to finish that project at some point.

The other thing is this go.hid seems to be for only 1 device at a time - I can have several HID devices I am wanting to open and control in a single system.  I was thinking of modifying this package to allow for several devices opened and managed via a uniqud id (e.g. a combination of the usb busid for the device).

Humm, these replies have given me renewed interest in the project.  :+1:

**Comment by GeertJohan** [comment]
This project is discontinued, please try [karalabe/hid](https://github.com/karalabe/hid) for you Go hid needs :)
